language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dharshan-git/docker-react -f Dockerfile.dev .

script:
  - docker run dharshan-git/docker-react npm run test -- --coverage
